# Generated by Django 5.2 on 2026-01-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='achievement_Type',
            new_name='achievement_type',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='profieciency',
            new_name='proficiency',
        ),
    ]
