# Generated by Django 6.1 on 2026-08-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_experience_options_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_pdf_ai_ml',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
