# Generated by Django 6.1 on 2026-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_content_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='apply_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='posted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('portfolio', 'Portfolio Contact Form'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('job_board', 'Job Board'), ('github', 'GitHub'), ('job_scan', 'Automated Job Scan'), ('email', 'Inbound Email'), ('manual', 'Manually Added'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('applied', 'Applied'), ('replied', 'Replied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
