# Generated by Django 6.1 on 2026-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_apply_url_lead_external_id_lead_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('portfolio', 'Portfolio Contact Form'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('job_board', 'Job Board'), ('application_form', 'Application Form'), ('github', 'GitHub'), ('job_scan', 'Automated Job Scan'), ('email', 'Inbound Email'), ('manual', 'Manually Added'), ('other', 'Other')], default='manual', max_length=20),
        ),
    ]
