# Generated by Django 6.1 on 2026-08-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_replied_at_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='resume_variant',
            field=models.CharField(blank=True, choices=[('backend', 'Backend / SDE'), ('ai_ml', 'AI / ML')], max_length=20),
        ),
    ]
