# Generated by Django 5.2 on 2026-08-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_resume_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('matched_leads', models.IntegerField(default=0)),
                ('ok', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('email_sent', 'Email Sent'), ('email_received', 'Reply Received'), ('email_draft', 'Email Drafted'), ('stage_change', 'Stage Change'), ('call', 'Call'), ('meeting', 'Meeting'), ('created', 'Created')], default='note', max_length=20),
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=300, unique=True)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, max_length=300)),
                ('references', models.TextField(blank=True)),
                ('thread_key', models.CharField(blank=True, db_index=True, max_length=300)),
                ('from_email', models.EmailField(db_index=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_email', models.CharField(blank=True, max_length=400)),
                ('cc_email', models.CharField(blank=True, max_length=400)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.CharField(blank=True, max_length=300)),
                ('has_attachments', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='crm.lead')),
                ('replies_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='crm.outreachemail')),
            ],
            options={
                'ordering': ['-sent_at', '-synced_at'],
                'indexes': [models.Index(fields=['is_archived', '-sent_at'], name='crm_inbound_is_arch_94f90e_idx'), models.Index(fields=['is_read'], name='crm_inbound_is_read_68cd51_idx')],
            },
        ),
    ]
