# Generated by Django 6.1 on 2026-08-26 17:17

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_mailsynclog_outreachemail_in_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachemail',
            name='attach_resume',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=crm.models._attachment_storage, upload_to='email_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.outreachemail')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
